FROM eclipse-temurin:17

LABEL mentainer = "haripara2014@gmail.com"

WORKDIR /app

COPY target/todoManagement-0.0.1-SNAPSHOT.jar /app/todoManagement.jar

ENTRYPOINT ["java", "-jar", "todoManagement.jar"]